=== ViktorEdfalk/webcert/web/src/test/resources/jsonschema/webcert-texter.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string"
    },
    "intygsTyp": {
      "type": "string"
    },
    "validFrom": {
      "type": "string"
    },
    "validTo": {
      "type": "string"
    },
    "texter": {
      "type": "object"
    },
    "tillaggsfragor": {
      "id": "http://jsonschema.net/tillaggsfragor",
      "type": "array",
      "items": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string"
            },
            "text": {
              "type": "string"
            },
            "help": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "text",
            "help"
          ]
        }
      ]
    }
  },
  "required": [
    "version",
    "intygsTyp"
  ]
}

=== ViktorEdfalk/webcert/test/webcertTestTools/testdata/luse_questions.json
{"version":"0.9","intygsTyp":"luse","validFrom":"2015-12-15","texter":{"DFR_1.1.HLP":"TBD","DFR_1.1.RBK":"Typ av underlag för utlåtandet","DFR_1.2.HLP":"TBD","DFR_1.2.RBK":"Datum","DFR_1.3.HLP":"TBD","DFR_1.3.RBK":"Annat underlag för utlåtandet","DFR_10.1.HLP":"TBD","DFR_10.1.RBK":"Uppmärksamhet och koncentration","DFR_11.1.HLP":"TBD","DFR_11.1.RBK":"Annan psykisk funktion","DFR_12.1.HLP":"TBD","DFR_12.1.RBK":"Syn, hörsel och tal","DFR_13.1.HLP":"TBD","DFR_13.1.RBK":"Balans/koordination, motorik och smärta","DFR_14.1.HLP":"TBD","DFR_14.1.RBK":"Annan kroppslig funktion","DFR_17.1.HLP":"TBD","DFR_17.1.RBK":"Vad har patienten svårt att göra på grund av den eller de funktionsnedsättningar som beskrivs ovan? Ge konkreta exempel","DFR_18.1.HLP":"TBD","DFR_18.1.RBK":"Avslutade medicinska behandlingar/åtgärder. Ange också under vilka perioder de pågick och vilka resultat de gav.","DFR_19.1.HLP":"TBD","DFR_19.1.RBK":"Pågående medicinska behandlingar/åtgärder och ansvarig vårdenhet.","DFR_2.1.HLP":"TBD","DFR_2.1.RBK":"Jag har känt patienten seden den","DFR_20.1.HLP":"TBD","DFR_20.1.RBK":"Planerade medicinska behandlingar/åtgärder. Ange om möjligt tidplan och ansvarig vårdenhet.","DFR_21.1.HLP":"TBD","DFR_21.1.RBK":"Substansintag (ordinerade läkemedel, alkohol, tobak och övriga substansintag)","DFR_22.1.HLP":"TBD","DFR_22.1.RBK":"Hur bedömer du att patientens medicinska förutsättningar för arbete, helt eller delvis, kan utvecklas över tid?","DFR_23.1.HLP":"Beskriv här om patienten har särskilt goda resurser inom något område eller har några speciella förmågor som kan tas till vara.","DFR_23.1.RBK":"Beskriv vad patienten kan göra trots sin sjukdom eller sina begränsningar.","DFR_25.1.HLP":"TBD","DFR_25.1.RBK":"Övriga upplysningar","DFR_26.1.HLP":"TBD","DFR_26.1.RBK":"Jag önskar att Försökringskassan kontaktar mig.","DFR_26.2.HLP":"TBD","DFR_26.2.RBK":"Ange gärna varför du vill ha kontakt.","DFR_3.1.HLP":"TBD","DFR_3.1.RBK":"Finns det andra medicinska utredningar eller underlag som är relevanta för bedömningen?","DFR_4.1.HLP":"TBD","DFR_4.1.RBK":"Ange utredning och underlag","DFR_4.2.RBK":"Datum","DFR_4.3.HLP":"Skriv exempelvis Neuropsykiatriska kliniken på X-stads sjukhus eller om patienten själv kommer att bifoga utredningen till sin ansökan.","DFR_4.3.RBK":"Var kan Försäkringskassan få information om utredningen?","DFR_5.1.HLP":"TBD","DFR_5.1.RBK":"Sjukdomsförlopp för aktuella sjukdomar av betydelse","DFR_6.1.HLP":"TBD","DFR_6.1.RBK":"Diagnostext","DFR_6.2.HLP":"TBD","DFR_6.2.RBK":"Diagnoskod enligt ICD-10 SE","DFR_7.1.HLP":"TBD","DFR_7.1.RBK":"När och var ställdes diagnosen/diagnoserna?","DFR_7.2.HLP":"Möjliga anledningar kan vara:\n- att det var länge sedan utredningen gjordes\n- att ny bedömning har rekommenderats i tidigare utlåtande eller\n- att den kliniska bilden avviker från vad som kan förväntas utifrån ställd diagnos","DFR_7.2.RBK":"Finns det skäl att göra en ny bedömning av diagnosen/diagnoserna?","DFR_8.1.HLP":"TBD","DFR_8.1.RBK":"Intellektuell funktion","DFR_9.1.HLP":"TBD","DFR_9.1.RBK":"Kommunikation och social interaktion","DFR_9001.1.HLP":"Ange din skostorlek.","DFR_9001.1.RBK":"Vilken skostorlek har du?","DFR_9002.1.HLP":"Ange din längd i centimeter (cm).","DFR_9002.1.RBK":"Hur lång är du?","FRG_1.HLP":"TBD","FRG_1.RBK":"Välj typ av underlag för utlåtandet och datum","FRM_1":"Vad är sjukersättning?\n\tSjukersättning är en ersättning för personer mellan 30 och 64 år som har nedsatt arbetsförmåga på grund av sjukdom, skada eller funktionsnedsättning. Beroende på hur mycket arbetsförmågan är nedsatt kan man få en fjärdedels, halv, tre fjärdedels eller hel sjukersättning. Man kan få sjukersättning om Försäkringskassan bedömer att arbetsförmågan är nedsatt med minst 25 procent för all överskådlig framtid och att alla rehabiliteringsmöjligheter är uttömda.\n","FRM_2":"Vad är sjukersättning?\n\tSjukersättning är en ersättning för personer mellan 30 och 64 år som har nedsatt arbetsförmåga på grund av sjukdom, skada eller funktionsnedsättning. Beroende på hur mycket arbetsförmågan är nedsatt kan man få en fjärdedels, halv, tre fjärdedels eller hel sjukersättning.\n\t\n\tFörutsättningar för att få sjukersättning\n\tFörsäkringskassan bedömer arbetsförmågan i förhållande till alla arbeten på hela arbetsmarknaden, alltså även till särskilt anpassade arbeten och anställningar med lönebidrag. Man kan få sjukersättning om Försäkringskassan bedömer att arbetsförmågan är nedsatt med minst 25 procent för all överskådlig framtid och att alla rehabiliteringsmöjligheter är uttömda. Den som ansöker om sjukersättning ska skicka med ett läkarutlåtande. I pågående sjukpenningärende kan också Försäkringskassan på eget initiativ begära ett läkarutlåtande från behandlande läkare.","KAT_1.HLP":"Motivera under \"Övriga upplysningar\" i de fall någon undersökning av patienten inte varit aktuell.","KAT_1.RBK":"Utlåtandet är baserat på","KAT_10.HLP":"Försäkringskassans handläggare tar kontakt med dig när underlaget har kommit in och handläggningen kan påbörjas.","KAT_10.RBK":"Vill du att Försäkringskassan kontaktar dig?","KAT_2.HLP":"TBD","KAT_2.RBK":"Andra medicinska utredningar och underlag","KAT_3.HLP":"TBD","KAT_3.RBK":"Sjukdomsförlopp","KAT_4.HLP":"Ange samtliga diagnoser som orsakar nedsatt arbetsförmåga.Huvuddiagnosen för arbetsförmågans nedsättning anges först.","KAT_4.RBK":"Diagnos/diagnoser som orsakar nedsatt arbetsförmåga","KAT_5.HLP":"Den information som Försäkringskassan efterfrågar inom de olika områdena är \nde av läkaren observerade funktionsnedsättningar (direkt/indirekt) med avvikelser i \nstatus men även sådana som framkommit hos psykolog eller i annan \nmedicinsk utredning.","KAT_5.RBK":"Funktionsnedsättning - beskriv patientens funktionsnedsättning inom de områden som är relevanta för arbetsförmågan.","KAT_6.HLP":"Ge konkreta exempel på situationer och aktiviteter i patientens sysselsättning där \nsvårigheter uppstår. Beskriv hur ofta dessa situationer uppstår och graden av \npatientens besvär.","KAT_6.RBK":"Aktivitetsbegränsning","KAT_7.HLP":"TBD","KAT_7.RBK":"Medicinsk behandling","KAT_8.HLP":"TBD","KAT_8.RBK":"Medicinska förutsättningar för arbete","KAT_9.HLP":"TBD","KAT_9.RBK":"Övriga upplysningar","KAT_9999.HLP":"TBD","KAT_9999.RBK":"Tilläggsfrågor","KV_FKMU_0001.1.HLP":"Här finns en hjälptext för min undersökning av patienten.","KV_FKMU_0001.1.RBK":"Min undersökning av patienten.","KV_FKMU_0001.2.HLP":"Här finns en hjälptext för min telefonkontakt med patienten.","KV_FKMU_0001.2.RBK":"Min telefonkontakt med patienten","KV_FKMU_0001.3.HLP":"Här finns en hjälptext för journaluppgifter från den.","KV_FKMU_0001.3.RBK":"Journaluppgifter från den","KV_FKMU_0001.4.HLP":"Här finns en hjälptext för anhörigs beskrivning av patienten.","KV_FKMU_0001.4.RBK":"Anhörigs beskrivning av patienten","KV_FKMU_0001.5.HLP":"Här finns en hjälptext för Annat.","KV_FKMU_0001.5.RBK":"Annat"},"tillaggsfragor":[{"id":"9001","text":"Vilken skostorlek har du?","help":"Ange din skostorlek."},{"id":"9002","text":"Hur lång är du?","help":"Ange din längd i centimeter (cm)."}]}
